# SonarQube project metadata
sonar.projectKey=jenkins-nexus-cicd
sonar.projectName=jenkins-nexus-cicd
sonar.projectVersion=1.0.0

# Source and test paths
sonar.sources=src/main/java
sonar.tests=src/test/java

# Java binary and report paths
sonar.java.binaries=target/classes
sonar.junit.reportPaths=target/surefire-reports

# Encoding
sonar.sourceEncoding=UTF-8
